#!/usr/bin/env node
/**
 * prebuild.js — Bakes AI-AGENT-REFERENCE.md into a TypeScript module
 * so the CLI can ship the content without a runtime file read.
 *
 * Run automatically via `npm run prebuild` (called before `tsc`).
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..", "..", "..");

const markdownPath = join(repoRoot, "AI-AGENT-REFERENCE.md");
const outDir = join(__dirname, "..", "src", "generated");
const outPath = join(outDir, "agent-reference.ts");

const content = readFileSync(markdownPath, "utf8");

mkdirSync(outDir, { recursive: true });

writeFileSync(
  outPath,
  `// Auto-generated by scripts/prebuild.js — do not edit manually.\n` +
    `// Source: AI-AGENT-REFERENCE.md\n\n` +
    `export const agentReference = ${JSON.stringify(content)};\n`,
);

console.log("prebuild: baked AI-AGENT-REFERENCE.md → src/generated/agent-reference.ts");
